namespace KinoShare.Core.Models;

/// <summary>
/// A temporary local Windows account created for a single sharing session.
/// The password is generated by the app and shown to the user once, unless a
/// remembered credential is configured (in which case it is reused).
/// </summary>
/// <param name="Username">The local account name.</param>
/// <param name="Password">The account password. Never log; may be persisted encrypted by <c>IDeviceCredentialStore</c>.</param>
public sealed record TemporaryUser(string Username, string Password)
{
    /// <summary>
    /// The fixed account name used by KinoShare for all sessions.
    /// A leftover account with this name is reused and cleaned up.
    /// </summary>
    public const string DefaultUsername = "kinoshare";
}
